import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type LangCode = "en" | "ta" | "hi" | "te" | "kn" | "ml" | "bn" | "mr" | "gu" | "pa" | "or";

export interface Translations {
  appSubtitle: string;
  navNewAnalysis: string;
  navDashboard: string;
  formTitle: string;
  formSubtitle: string;
  sectionSampleInfo: string;
  sectionSampleInfoDesc: string;
  sectionSoilReadings: string;
  labelFarmerName: string;
  labelLocation: string;
  labelSeason: string;
  labelWater: string;
  labelPh: string;
  labelNitrogen: string;
  labelPhosphorus: string;
  labelPotassium: string;
  labelMoisture: string;
  labelPreferredCrop: string;
  preferredCropHint: string;
  placeholderFarmerName: string;
  placeholderLocation: string;
  placeholderCrop: string;
  selectSeason: string;
  selectWater: string;
  seasonKharif: string;
  seasonRabi: string;
  seasonSummer: string;
  waterLow: string;
  waterMedium: string;
  waterHigh: string;
  btnGetRecommendations: string;
  btnAnalyzing: string;
  btnDetectLocation: string;
  btnDetecting: string;
  btnAnalyzeAnother: string;
  gpsLocationDetected: string;
  gpsDetecting: string;
  gpsError: string;
  weatherTitle: string;
  weatherTemp: string;
  weatherHumidity: string;
  weatherGpsNote: string;
  resultsTitle: string;
  resultsGeneratedOn: string;
  resultsCropsTitle: string;
  resultsCropsDesc: string;
  resultsSoilCorrections: string;
  resultsFertilizerPlan: string;
  resultsNoCorrections: string;
  resultsSuitabilityScore: string;
  resultsDosage: string;
  resultsTiming: string;
  resultsExplanationTitle: string;
  resultsEnglishLabel: string;
  adminTitle: string;
  adminSubtitle: string;
  adminTotalSubmissions: string;
  adminTodayAnalyses: string;
  adminAvgPh: string;
  adminTopCrop: string;
  adminRecentSubmissions: string;
  adminTopCrops: string;
  adminSeasonBreakdown: string;
  detectedLanguage: string;
}

const translations: Record<LangCode, Translations> = {
  en: {
    appSubtitle: "Soil Health Advisor",
    navNewAnalysis: "New Analysis",
    navDashboard: "Dashboard",
    formTitle: "Soil Health Analysis",
    formSubtitle: "Enter your soil test details to get personalized crop recommendations and fertilizer advice.",
    sectionSampleInfo: "Sample Information",
    sectionSampleInfoDesc: "Provide basic details about your farm and the soil sample.",
    sectionSoilReadings: "Soil Test Readings",
    labelFarmerName: "Farmer Name (Optional)",
    labelLocation: "District / Location",
    labelSeason: "Growing Season",
    labelWater: "Water Availability",
    labelPh: "pH Level (0-14)",
    labelNitrogen: "Nitrogen (N) kg/ha",
    labelPhosphorus: "Phosphorus (P) kg/ha",
    labelPotassium: "Potassium (K) kg/ha",
    labelMoisture: "Moisture Content (%)",
    labelPreferredCrop: "Preferred Crop (Optional)",
    preferredCropHint: "If you already have a crop in mind, tell us so we can tailor advice.",
    placeholderFarmerName: "e.g. Ramesh Kumar",
    placeholderLocation: "e.g. Pune, Maharashtra",
    placeholderCrop: "e.g. Wheat, Rice, Cotton",
    selectSeason: "Select Season",
    selectWater: "Select Availability",
    seasonKharif: "Kharif (Monsoon)",
    seasonRabi: "Rabi (Winter)",
    seasonSummer: "Summer (Zaid)",
    waterLow: "Low (Rainfed only)",
    waterMedium: "Medium (Partial irrigation)",
    waterHigh: "High (Full irrigation)",
    btnGetRecommendations: "Get Recommendations",
    btnAnalyzing: "Analyzing Sample...",
    btnDetectLocation: "Detect My Location",
    btnDetecting: "Detecting...",
    btnAnalyzeAnother: "Analyze Another Sample",
    gpsLocationDetected: "Location detected",
    gpsDetecting: "Detecting your location...",
    gpsError: "Could not detect location",
    weatherTitle: "Live Weather at Your Location",
    weatherTemp: "Temperature",
    weatherHumidity: "Humidity",
    weatherGpsNote: "Real-time data from your GPS location",
    resultsTitle: "Analysis Results",
    resultsGeneratedOn: "Generated on",
    resultsCropsTitle: "Top Recommended Crops",
    resultsCropsDesc: "Based on your soil's nutrient profile and season.",
    resultsSoilCorrections: "Soil Corrections",
    resultsFertilizerPlan: "Fertilizer Plan",
    resultsNoCorrections: "Soil balance is good. No major corrections needed.",
    resultsSuitabilityScore: "Suitability Score",
    resultsDosage: "Dosage",
    resultsTiming: "Timing",
    resultsExplanationTitle: "Detailed Advice",
    resultsEnglishLabel: "English",
    adminTitle: "Admin Dashboard",
    adminSubtitle: "Overview of all soil analysis submissions across the network.",
    adminTotalSubmissions: "Total Submissions",
    adminTodayAnalyses: "Today's Analyses",
    adminAvgPh: "Average pH Level",
    adminTopCrop: "Top Crop Request",
    adminRecentSubmissions: "Recent Submissions",
    adminTopCrops: "Top Recommended Crops",
    adminSeasonBreakdown: "Seasonal Breakdown",
    detectedLanguage: "Detected Language",
  },
  ta: {
    appSubtitle: "மண் ஆரோக்கிய ஆலோசகர்",
    navNewAnalysis: "புதிய பகுப்பாய்வு",
    navDashboard: "கட்டுப்பாட்டு பலகை",
    formTitle: "மண் ஆரோக்கிய பகுப்பாய்வு",
    formSubtitle: "தனிப்பயனாக்கப்பட்ட பயிர் பரிந்துரைகளுக்கு உங்கள் மண் பரிசோதனை விவரங்களை உள்ளிடவும்.",
    sectionSampleInfo: "மாதிரி தகவல்",
    sectionSampleInfoDesc: "உங்கள் விவசாய நிலம் மற்றும் மண் மாதிரி பற்றிய அடிப்படை விவரங்களை வழங்கவும்.",
    sectionSoilReadings: "மண் பரிசோதனை அளவீடுகள்",
    labelFarmerName: "விவசாயியின் பெயர் (விருப்பமானது)",
    labelLocation: "மாவட்டம் / இடம்",
    labelSeason: "பயிர் சீசன்",
    labelWater: "நீர் கிடைக்கும் தன்மை",
    labelPh: "pH அளவு (0-14)",
    labelNitrogen: "நைட்ரஜன் (N) கி.கி/ஹெக்டேர்",
    labelPhosphorus: "பாஸ்பரஸ் (P) கி.கி/ஹெக்டேர்",
    labelPotassium: "பொட்டாசியம் (K) கி.கி/ஹெக்டேர்",
    labelMoisture: "ஈரப்பதம் (%)",
    labelPreferredCrop: "விரும்பிய பயிர் (விருப்பமானது)",
    preferredCropHint: "ஒரு குறிப்பிட்ட பயிர் மனதில் இருந்தால், சொல்லுங்கள் — தகுந்த ஆலோசனை வழங்குவோம்.",
    placeholderFarmerName: "எ.கா. இராமசாமி",
    placeholderLocation: "எ.கா. கோயம்புத்தூர், தமிழ்நாடு",
    placeholderCrop: "எ.கா. நெல், கோதுமை, பருத்தி",
    selectSeason: "சீசன் தேர்வு செய்யவும்",
    selectWater: "தேர்வு செய்யவும்",
    seasonKharif: "காரீஃ (மழைக்காலம்)",
    seasonRabi: "ரபி (குளிர்காலம்)",
    seasonSummer: "கோடை (ஜைத்)",
    waterLow: "குறைவு (மழை நீர் மட்டும்)",
    waterMedium: "நடுத்தர (பகுதி நீர்ப்பாசனம்)",
    waterHigh: "அதிகம் (முழு நீர்ப்பாசனம்)",
    btnGetRecommendations: "பரிந்துரைகளை பெறுங்கள்",
    btnAnalyzing: "பகுப்பாய்வு செய்கிறது...",
    btnDetectLocation: "என் இடத்தை கண்டறி",
    btnDetecting: "கண்டறிகிறது...",
    btnAnalyzeAnother: "மறு மாதிரி பகுப்பாய்வு",
    gpsLocationDetected: "இடம் கண்டறியப்பட்டது",
    gpsDetecting: "உங்கள் இடத்தை கண்டறிகிறது...",
    gpsError: "இடத்தை கண்டறிய முடியவில்லை",
    weatherTitle: "உங்கள் இடத்தில் நேரடி வானிலை",
    weatherTemp: "வெப்பநிலை",
    weatherHumidity: "ஈரப்பதம்",
    weatherGpsNote: "GPS மூலம் நேரடி தரவு",
    resultsTitle: "பகுப்பாய்வு முடிவுகள்",
    resultsGeneratedOn: "உருவாக்கப்பட்ட தேதி",
    resultsCropsTitle: "சிறந்த பரிந்துரைக்கப்பட்ட பயிர்கள்",
    resultsCropsDesc: "உங்கள் மண்ணின் ஊட்டச்சத்து மற்றும் சீசன் அடிப்படையில்.",
    resultsSoilCorrections: "மண் திருத்தங்கள்",
    resultsFertilizerPlan: "உர திட்டம்",
    resultsNoCorrections: "மண் நிலை சீராக உள்ளது. பெரிய திருத்தங்கள் தேவையில்லை.",
    resultsSuitabilityScore: "பொருத்தம் மதிப்பெண்",
    resultsDosage: "அளவு",
    resultsTiming: "நேரம்",
    resultsExplanationTitle: "விரிவான ஆலோசனை",
    resultsEnglishLabel: "ஆங்கிலம்",
    adminTitle: "நிர்வாக கட்டுப்பாட்டு பலகை",
    adminSubtitle: "அனைத்து மண் பகுப்பாய்வுகளின் கண்ணோட்டம்.",
    adminTotalSubmissions: "மொத்த சமர்ப்பிப்புகள்",
    adminTodayAnalyses: "இன்றைய பகுப்பாய்வுகள்",
    adminAvgPh: "சராசரி pH அளவு",
    adminTopCrop: "முன்னணி பயிர் கோரிக்கை",
    adminRecentSubmissions: "சமீபத்திய சமர்ப்பிப்புகள்",
    adminTopCrops: "முன்னணி பரிந்துரைக்கப்பட்ட பயிர்கள்",
    adminSeasonBreakdown: "சீசன் பிரிவு",
    detectedLanguage: "கண்டறியப்பட்ட மொழி",
  },
  hi: {
    appSubtitle: "मिट्टी स्वास्थ्य सलाहकार",
    navNewAnalysis: "नया विश्लेषण",
    navDashboard: "डैशबोर्ड",
    formTitle: "मिट्टी स्वास्थ्य विश्लेषण",
    formSubtitle: "व्यक्तिगत फसल सिफारिशें और उर्वरक सलाह पाने के लिए अपने मिट्टी परीक्षण का विवरण दर्ज करें।",
    sectionSampleInfo: "नमूना जानकारी",
    sectionSampleInfoDesc: "अपनी खेती और मिट्टी के नमूने की बुनियादी जानकारी दें।",
    sectionSoilReadings: "मिट्टी परीक्षण मूल्य",
    labelFarmerName: "किसान का नाम (वैकल्पिक)",
    labelLocation: "जिला / स्थान",
    labelSeason: "फसल ऋतु",
    labelWater: "पानी की उपलब्धता",
    labelPh: "pH स्तर (0-14)",
    labelNitrogen: "नाइट्रोजन (N) कि.ग्रा./हेक्टेयर",
    labelPhosphorus: "फास्फोरस (P) कि.ग्रा./हेक्टेयर",
    labelPotassium: "पोटेशियम (K) कि.ग्रा./हेक्टेयर",
    labelMoisture: "नमी (%)",
    labelPreferredCrop: "पसंदीदा फसल (वैकल्पिक)",
    preferredCropHint: "यदि आपके मन में कोई फसल है, तो बताएं — हम उसके अनुसार सलाह देंगे।",
    placeholderFarmerName: "जैसे: रामेश कुमार",
    placeholderLocation: "जैसे: पुणे, महाराष्ट्र",
    placeholderCrop: "जैसे: गेहूं, धान, कपास",
    selectSeason: "ऋतु चुनें",
    selectWater: "उपलब्धता चुनें",
    seasonKharif: "खरीफ (मानसून)",
    seasonRabi: "रबी (सर्दी)",
    seasonSummer: "जायद (गर्मी)",
    waterLow: "कम (केवल वर्षा)",
    waterMedium: "मध्यम (आंशिक सिंचाई)",
    waterHigh: "अधिक (पूर्ण सिंचाई)",
    btnGetRecommendations: "सिफारिशें प्राप्त करें",
    btnAnalyzing: "नमूना विश्लेषण हो रहा है...",
    btnDetectLocation: "मेरा स्थान पहचानें",
    btnDetecting: "पहचान रहा है...",
    btnAnalyzeAnother: "दूसरा नमूना जांचें",
    gpsLocationDetected: "स्थान पहचाना गया",
    gpsDetecting: "आपका स्थान पहचाना जा रहा है...",
    gpsError: "स्थान पहचाना नहीं जा सका",
    weatherTitle: "आपके स्थान का लाइव मौसम",
    weatherTemp: "तापमान",
    weatherHumidity: "आर्द्रता",
    weatherGpsNote: "GPS से वास्तविक समय डेटा",
    resultsTitle: "विश्लेषण परिणाम",
    resultsGeneratedOn: "तैयार की गई तिथि",
    resultsCropsTitle: "शीर्ष अनुशंसित फसलें",
    resultsCropsDesc: "आपकी मिट्टी के पोषक तत्वों और मौसम के आधार पर।",
    resultsSoilCorrections: "मिट्टी सुधार",
    resultsFertilizerPlan: "उर्वरक योजना",
    resultsNoCorrections: "मिट्टी संतुलन अच्छा है। कोई बड़ा सुधार नहीं चाहिए।",
    resultsSuitabilityScore: "उपयुक्तता स्कोर",
    resultsDosage: "खुराक",
    resultsTiming: "समय",
    resultsExplanationTitle: "विस्तृत सलाह",
    resultsEnglishLabel: "अंग्रेज़ी",
    adminTitle: "एडमिन डैशबोर्ड",
    adminSubtitle: "सभी मिट्टी विश्लेषण सबमिशन का अवलोकन।",
    adminTotalSubmissions: "कुल सबमिशन",
    adminTodayAnalyses: "आज के विश्लेषण",
    adminAvgPh: "औसत pH स्तर",
    adminTopCrop: "शीर्ष फसल अनुरोध",
    adminRecentSubmissions: "हालिया सबमिशन",
    adminTopCrops: "शीर्ष अनुशंसित फसलें",
    adminSeasonBreakdown: "मौसम विभाजन",
    detectedLanguage: "पहचानी गई भाषा",
  },
  te: {
    appSubtitle: "మట్టి ఆరోగ్య సలహాదారు",
    navNewAnalysis: "కొత్త విశ్లేషణ",
    navDashboard: "డాష్‌బోర్డ్",
    formTitle: "మట్టి ఆరోగ్య విశ్లేషణ",
    formSubtitle: "వ్యక్తిగత పంట సిఫారసులు పొందడానికి మీ మట్టి పరీక్ష వివరాలు నమోదు చేయండి.",
    sectionSampleInfo: "నమూనా సమాచారం",
    sectionSampleInfoDesc: "మీ వ్యవసాయ భూమి మరియు మట్టి నమూనా గురించి వివరాలు ఇవ్వండి.",
    sectionSoilReadings: "మట్టి పరీక్ష కొలతలు",
    labelFarmerName: "రైతు పేరు (ఐచ్ఛికం)",
    labelLocation: "జిల్లా / ప్రదేశం",
    labelSeason: "పంట సీజన్",
    labelWater: "నీటి లభ్యత",
    labelPh: "pH స్థాయి (0-14)",
    labelNitrogen: "నైట్రోజన్ (N) కి.గ్రా/హె.",
    labelPhosphorus: "భాస్వరం (P) కి.గ్రా/హె.",
    labelPotassium: "పొటాషియం (K) కి.గ్రా/హె.",
    labelMoisture: "తేమ శాతం (%)",
    labelPreferredCrop: "ఇష్టమైన పంట (ఐచ్ఛికం)",
    preferredCropHint: "మీకు ఒక పంట మనసులో ఉంటే చెప్పండి — తగిన సలహా ఇస్తాం.",
    placeholderFarmerName: "ఉదా: రామయ్య",
    placeholderLocation: "ఉదా: గుంటూరు, ఆంధ్రప్రదేశ్",
    placeholderCrop: "ఉదా: వరి, జొన్న, పత్తి",
    selectSeason: "సీజన్ ఎంచుకోండి",
    selectWater: "ఎంచుకోండి",
    seasonKharif: "ఖరీఫ్ (వర్షాకాలం)",
    seasonRabi: "రబీ (శీతాకాలం)",
    seasonSummer: "వేసవి",
    waterLow: "తక్కువ (వర్షం మాత్రమే)",
    waterMedium: "మధ్యస్థం (పాక్షిక నీటిపారుదల)",
    waterHigh: "అధికం (పూర్తి నీటిపారుదల)",
    btnGetRecommendations: "సిఫారసులు పొందండి",
    btnAnalyzing: "నమూనా విశ్లేషణ అవుతోంది...",
    btnDetectLocation: "నా స్థానం గుర్తించు",
    btnDetecting: "గుర్తిస్తోంది...",
    btnAnalyzeAnother: "మరో నమూనా విశ్లేషించు",
    gpsLocationDetected: "స్థానం గుర్తించబడింది",
    gpsDetecting: "మీ స్థానాన్ని గుర్తిస్తోంది...",
    gpsError: "స్థానం గుర్తించడం సాధ్యం కాలేదు",
    weatherTitle: "మీ స్థానంలో నేటి వాతావరణం",
    weatherTemp: "ఉష్ణోగ్రత",
    weatherHumidity: "తేమ",
    weatherGpsNote: "GPS నుండి నేరుగా డేటా",
    resultsTitle: "విశ్లేషణ ఫలితాలు",
    resultsGeneratedOn: "తయారైన తేదీ",
    resultsCropsTitle: "అగ్రశ్రేణి పంట సిఫారసులు",
    resultsCropsDesc: "మీ మట్టి పోషకాలు మరియు సీజన్ ఆధారంగా.",
    resultsSoilCorrections: "మట్టి సవరణలు",
    resultsFertilizerPlan: "ఎరువు ప్రణాళిక",
    resultsNoCorrections: "మట్టి సమతుల్యత మంచిది. పెద్ద సవరణలు అవసరం లేదు.",
    resultsSuitabilityScore: "అనుకూలత స్కోర్",
    resultsDosage: "మోతాదు",
    resultsTiming: "సమయం",
    resultsExplanationTitle: "వివరణాత్మక సలహా",
    resultsEnglishLabel: "ఆంగ్లం",
    adminTitle: "అడ్మిన్ డాష్‌బోర్డ్",
    adminSubtitle: "అన్ని మట్టి విశ్లేషణ సమర్పణల సమగ్ర వీక్షణ.",
    adminTotalSubmissions: "మొత్తం సమర్పణలు",
    adminTodayAnalyses: "నేటి విశ్లేషణలు",
    adminAvgPh: "సగటు pH స్థాయి",
    adminTopCrop: "అగ్రశ్రేణి పంట అభ్యర్థన",
    adminRecentSubmissions: "ఇటీవలి సమర్పణలు",
    adminTopCrops: "అగ్రశ్రేణి సిఫారసు పంటలు",
    adminSeasonBreakdown: "సీజన్ వివరణ",
    detectedLanguage: "గుర్తించిన భాష",
  },
  kn: {
    appSubtitle: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಸಲಹೆಗಾರ",
    navNewAnalysis: "ಹೊಸ ವಿಶ್ಲೇಷಣೆ",
    navDashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    formTitle: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ ವಿಶ್ಲೇಷಣೆ",
    formSubtitle: "ವೈಯಕ್ತಿಕ ಬೆಳೆ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಮಣ್ಣು ಪರೀಕ್ಷೆಯ ವಿವರಗಳನ್ನು ನಮೂದಿಸಿ.",
    sectionSampleInfo: "ಮಾದರಿ ಮಾಹಿತಿ",
    sectionSampleInfoDesc: "ನಿಮ್ಮ ಜಮೀನು ಮತ್ತು ಮಣ್ಣಿನ ಮಾದರಿಯ ಮೂಲ ವಿವರಗಳನ್ನು ನೀಡಿ.",
    sectionSoilReadings: "ಮಣ್ಣು ಪರೀಕ್ಷೆ ಮಾಪನಗಳು",
    labelFarmerName: "ರೈತರ ಹೆಸರು (ಐಚ್ಛಿಕ)",
    labelLocation: "ಜಿಲ್ಲೆ / ಸ್ಥಳ",
    labelSeason: "ಬೆಳೆ ಋತು",
    labelWater: "ನೀರಿನ ಲಭ್ಯತೆ",
    labelPh: "pH ಮಟ್ಟ (0-14)",
    labelNitrogen: "ಸಾರಜನಕ (N) ಕಿ.ಗ್ರಾ/ಹೆ.",
    labelPhosphorus: "ರಂಜಕ (P) ಕಿ.ಗ್ರಾ/ಹೆ.",
    labelPotassium: "ಪೊಟ್ಯಾಷಿಯಂ (K) ಕಿ.ಗ್ರಾ/ಹೆ.",
    labelMoisture: "ತೇವಾಂಶ (%)",
    labelPreferredCrop: "ಇಷ್ಟದ ಬೆಳೆ (ಐಚ್ಛಿಕ)",
    preferredCropHint: "ನಿಮ್ಮ ಮನಸ್ಸಿನಲ್ಲಿ ಒಂದು ಬೆಳೆ ಇದ್ದರೆ, ತಿಳಿಸಿ — ಸೂಕ್ತ ಸಲಹೆ ನೀಡುತ್ತೇವೆ.",
    placeholderFarmerName: "ಉದಾ: ರಾಮಯ್ಯ",
    placeholderLocation: "ಉದಾ: ಬೆಳಗಾವಿ, ಕರ್ನಾಟಕ",
    placeholderCrop: "ಉದಾ: ಭತ್ತ, ಜೋಳ, ಹತ್ತಿ",
    selectSeason: "ಋತು ಆಯ್ಕೆ ಮಾಡಿ",
    selectWater: "ಆಯ್ಕೆ ಮಾಡಿ",
    seasonKharif: "ಖರೀಫ್ (ಮಳೆಗಾಲ)",
    seasonRabi: "ರಬಿ (ಚಳಿಗಾಲ)",
    seasonSummer: "ಬೇಸಿಗೆ",
    waterLow: "ಕಡಿಮೆ (ಮಳೆನೀರು ಮಾತ್ರ)",
    waterMedium: "ಮಧ್ಯಮ (ಭಾಗಶಃ ನೀರಾವರಿ)",
    waterHigh: "ಹೆಚ್ಚು (ಪೂರ್ಣ ನೀರಾವರಿ)",
    btnGetRecommendations: "ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ",
    btnAnalyzing: "ಮಾದರಿ ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    btnDetectLocation: "ನನ್ನ ಸ್ಥಳ ಪತ್ತೆ ಮಾಡಿ",
    btnDetecting: "ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    btnAnalyzeAnother: "ಮತ್ತೊಂದು ಮಾದರಿ ವಿಶ್ಲೇಷಿಸಿ",
    gpsLocationDetected: "ಸ್ಥಳ ಪತ್ತೆ ಮಾಡಲಾಗಿದೆ",
    gpsDetecting: "ನಿಮ್ಮ ಸ್ಥಳ ಪತ್ತೆ ಮಾಡಲಾಗುತ್ತಿದೆ...",
    gpsError: "ಸ್ಥಳ ಪತ್ತೆ ಮಾಡಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ",
    weatherTitle: "ನಿಮ್ಮ ಸ್ಥಳದ ಲೈವ್ ಹವಾಮಾನ",
    weatherTemp: "ತಾಪಮಾನ",
    weatherHumidity: "ತೇವಾಂಶ",
    weatherGpsNote: "GPS ಮೂಲಕ ನೇರ ಡೇಟಾ",
    resultsTitle: "ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶಗಳು",
    resultsGeneratedOn: "ರಚಿಸಲಾದ ದಿನಾಂಕ",
    resultsCropsTitle: "ಅಗ್ರ ಶಿಫಾರಸು ಬೆಳೆಗಳು",
    resultsCropsDesc: "ನಿಮ್ಮ ಮಣ್ಣಿನ ಪೋಷಕಾಂಶ ಮತ್ತು ಋತು ಆಧಾರದಲ್ಲಿ.",
    resultsSoilCorrections: "ಮಣ್ಣು ಸುಧಾರಣೆ",
    resultsFertilizerPlan: "ಗೊಬ್ಬರ ಯೋಜನೆ",
    resultsNoCorrections: "ಮಣ್ಣಿನ ಸಮತೋಲನ ಉತ್ತಮವಾಗಿದೆ. ದೊಡ್ಡ ಸುಧಾರಣೆ ಅಗತ್ಯವಿಲ್ಲ.",
    resultsSuitabilityScore: "ಸೂಕ್ತತೆ ಅಂಕ",
    resultsDosage: "ಪ್ರಮಾಣ",
    resultsTiming: "ಸಮಯ",
    resultsExplanationTitle: "ವಿಸ್ತೃತ ಸಲಹೆ",
    resultsEnglishLabel: "ಇಂಗ್ಲಿಷ್",
    adminTitle: "ಆಡಳಿತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    adminSubtitle: "ಎಲ್ಲಾ ಮಣ್ಣು ವಿಶ್ಲೇಷಣೆ ಸಲ್ಲಿಕೆಗಳ ಅವಲೋಕನ.",
    adminTotalSubmissions: "ಒಟ್ಟು ಸಲ್ಲಿಕೆಗಳು",
    adminTodayAnalyses: "ಇಂದಿನ ವಿಶ್ಲೇಷಣೆಗಳು",
    adminAvgPh: "ಸರಾಸರಿ pH ಮಟ್ಟ",
    adminTopCrop: "ಅಗ್ರ ಬೆಳೆ ವಿನಂತಿ",
    adminRecentSubmissions: "ಇತ್ತೀಚಿನ ಸಲ್ಲಿಕೆಗಳು",
    adminTopCrops: "ಅಗ್ರ ಶಿಫಾರಸು ಬೆಳೆಗಳು",
    adminSeasonBreakdown: "ಋತು ವಿಭಾಗ",
    detectedLanguage: "ಪತ್ತೆ ಮಾಡಿದ ಭಾಷೆ",
  },
  ml: {
    appSubtitle: "മണ്ണ് ആരോഗ്യ ഉപദേഷ്ടാവ്",
    navNewAnalysis: "പുതിയ വിശകലനം",
    navDashboard: "ഡാഷ്‌ബോർഡ്",
    formTitle: "മണ്ണ് ആരോഗ്യ വിശകലനം",
    formSubtitle: "വ്യക്തിഗത വിള ശുപാർശകൾ ലഭിക്കാൻ മണ്ണ് പരിശോധനാ വിശദാംശങ്ങൾ നൽകുക.",
    sectionSampleInfo: "സാമ്പിൾ വിവരങ്ങൾ",
    sectionSampleInfoDesc: "നിങ്ങളുടെ കൃഷിസ്ഥലവും മണ്ണ് സാമ്പിളിനെ കുറിച്ചുള്ള അടിസ്ഥാന വിവരങ്ങൾ നൽകുക.",
    sectionSoilReadings: "മണ്ണ് പരിശോധന മൂല്യങ്ങൾ",
    labelFarmerName: "കർഷകന്റെ പേര് (ഓപ്ഷണൽ)",
    labelLocation: "ജില്ല / സ്ഥലം",
    labelSeason: "കൃഷി സീസൺ",
    labelWater: "ജലലഭ്യത",
    labelPh: "pH നില (0-14)",
    labelNitrogen: "നൈട്രജൻ (N) കി.ഗ്രാ/ഹെ.",
    labelPhosphorus: "ഫോസ്ഫറസ് (P) കി.ഗ്രാ/ഹെ.",
    labelPotassium: "പൊട്ടാസ്യം (K) കി.ഗ്രാ/ഹെ.",
    labelMoisture: "ഈർപ്പം (%)",
    labelPreferredCrop: "ഇഷ്ടപ്പെട്ട വിള (ഓപ്ഷണൽ)",
    preferredCropHint: "ഒരു വിള മനസ്സിൽ ഉണ്ടെങ്കിൽ പറയൂ — ഉചിതമായ ഉപദേശം നൽകാം.",
    placeholderFarmerName: "ഉദാ: രാമൻ",
    placeholderLocation: "ഉദാ: തൃശ്ശൂർ, കേരളം",
    placeholderCrop: "ഉദാ: നെല്ല്, ചേന, തെങ്ങ്",
    selectSeason: "സീസൺ തിരഞ്ഞെടുക്കുക",
    selectWater: "തിരഞ്ഞെടുക്കുക",
    seasonKharif: "ഖരീഫ് (മഴക്കാലം)",
    seasonRabi: "റബി (ശൈത്യകാലം)",
    seasonSummer: "വേനൽ",
    waterLow: "കുറവ് (മഴ മാത്രം)",
    waterMedium: "ഇടത്തരം (ഭാഗിക ജലസേചനം)",
    waterHigh: "കൂടുതൽ (പൂർണ ജലസേചനം)",
    btnGetRecommendations: "ശുപാർശകൾ ലഭിക്കുക",
    btnAnalyzing: "സാമ്പിൾ വിശകലനം ചെയ്യുന്നു...",
    btnDetectLocation: "എന്റെ സ്ഥലം കണ്ടെത്തുക",
    btnDetecting: "കണ്ടെത്തുന്നു...",
    btnAnalyzeAnother: "മറ്റൊരു സാമ്പിൾ വിശകലനം",
    gpsLocationDetected: "സ്ഥലം കണ്ടെത്തി",
    gpsDetecting: "നിങ്ങളുടെ സ്ഥലം കണ്ടെത്തുന്നു...",
    gpsError: "സ്ഥലം കണ്ടെത്താൻ കഴിഞ്ഞില്ല",
    weatherTitle: "നിങ്ങളുടെ സ്ഥലത്തെ ലൈവ് കാലാവസ്ഥ",
    weatherTemp: "താപനില",
    weatherHumidity: "ഈർപ്പം",
    weatherGpsNote: "GPS വഴി നേരിട്ടുള്ള ഡേറ്റ",
    resultsTitle: "വിശകലന ഫലങ്ങൾ",
    resultsGeneratedOn: "നിർമ്മിച്ച തീയതി",
    resultsCropsTitle: "ഏറ്റവും ശുപാർശ ചെയ്ത വിളകൾ",
    resultsCropsDesc: "നിങ്ങളുടെ മണ്ണിന്റെ പോഷകഗുണവും സീസണും ആധാരമാക്കി.",
    resultsSoilCorrections: "മണ്ണ് തിരുത്തലുകൾ",
    resultsFertilizerPlan: "വളം പദ്ധതി",
    resultsNoCorrections: "മണ്ണ് സന്തുലിതം നല്ലതാണ്. വലിയ തിരുത്തലുകൾ ആവശ്യമില്ല.",
    resultsSuitabilityScore: "അനുയോജ്യത സ്കോർ",
    resultsDosage: "അളവ്",
    resultsTiming: "സമയം",
    resultsExplanationTitle: "വിശദമായ ഉപദേശം",
    resultsEnglishLabel: "ഇംഗ്ലീഷ്",
    adminTitle: "അഡ്മിൻ ഡാഷ്‌ബോർഡ്",
    adminSubtitle: "എല്ലാ മണ്ണ് വിശകലന സമർപ്പണങ്ങളുടെ അവലോകനം.",
    adminTotalSubmissions: "ആകെ സമർപ്പണങ്ങൾ",
    adminTodayAnalyses: "ഇന്നത്തെ വിശകലനങ്ങൾ",
    adminAvgPh: "ശരാശരി pH നില",
    adminTopCrop: "പ്രധാന വിള അഭ്യർഥന",
    adminRecentSubmissions: "സമീപകാല സമർപ്പണങ്ങൾ",
    adminTopCrops: "ഏറ്റവും ശുപാർശ ചെയ്ത വിളകൾ",
    adminSeasonBreakdown: "സീസൺ വിഭജനം",
    detectedLanguage: "കണ്ടെത്തിയ ഭാഷ",
  },
  bn: {
    appSubtitle: "মাটি স্বাস্থ্য উপদেষ্টা",
    navNewAnalysis: "নতুন বিশ্লেষণ",
    navDashboard: "ড্যাশবোর্ড",
    formTitle: "মাটি স্বাস্থ্য বিশ্লেষণ",
    formSubtitle: "ব্যক্তিগতকৃত ফসলের সুপারিশ পেতে আপনার মাটি পরীক্ষার বিবরণ দিন।",
    sectionSampleInfo: "নমুনা তথ্য",
    sectionSampleInfoDesc: "আপনার জমি ও মাটির নমুনা সম্পর্কে মূল তথ্য দিন।",
    sectionSoilReadings: "মাটি পরীক্ষার পাঠ",
    labelFarmerName: "কৃষকের নাম (ঐচ্ছিক)",
    labelLocation: "জেলা / স্থান",
    labelSeason: "ফসলের মৌসুম",
    labelWater: "জলের প্রাপ্যতা",
    labelPh: "pH মাত্রা (0-14)",
    labelNitrogen: "নাইট্রোজেন (N) কেজি/হেক্টর",
    labelPhosphorus: "ফসফরাস (P) কেজি/হেক্টর",
    labelPotassium: "পটাশিয়াম (K) কেজি/হেক্টর",
    labelMoisture: "আর্দ্রতা (%)",
    labelPreferredCrop: "পছন্দের ফসল (ঐচ্ছিক)",
    preferredCropHint: "কোনো ফসল মাথায় থাকলে জানান — সেই অনুযায়ী পরামর্শ দেব।",
    placeholderFarmerName: "যেমন: রামচন্দ্র দাস",
    placeholderLocation: "যেমন: মুর্শিদাবাদ, পশ্চিমবঙ্গ",
    placeholderCrop: "যেমন: ধান, গম, পাট",
    selectSeason: "মৌসুম বেছে নিন",
    selectWater: "বেছে নিন",
    seasonKharif: "খরিফ (বর্ষা)",
    seasonRabi: "রবি (শীত)",
    seasonSummer: "গ্রীষ্মকালীন",
    waterLow: "কম (শুধু বৃষ্টি)",
    waterMedium: "মাঝারি (আংশিক সেচ)",
    waterHigh: "বেশি (পূর্ণ সেচ)",
    btnGetRecommendations: "সুপারিশ পান",
    btnAnalyzing: "নমুনা বিশ্লেষণ হচ্ছে...",
    btnDetectLocation: "আমার অবস্থান সনাক্ত করুন",
    btnDetecting: "সনাক্ত হচ্ছে...",
    btnAnalyzeAnother: "আরেকটি নমুনা বিশ্লেষণ",
    gpsLocationDetected: "অবস্থান সনাক্ত হয়েছে",
    gpsDetecting: "আপনার অবস্থান সনাক্ত হচ্ছে...",
    gpsError: "অবস্থান সনাক্ত করা যায়নি",
    weatherTitle: "আপনার অবস্থানের লাইভ আবহাওয়া",
    weatherTemp: "তাপমাত্রা",
    weatherHumidity: "আর্দ্রতা",
    weatherGpsNote: "GPS থেকে সরাসরি তথ্য",
    resultsTitle: "বিশ্লেষণের ফলাফল",
    resultsGeneratedOn: "তৈরির তারিখ",
    resultsCropsTitle: "শীর্ষ সুপারিশকৃত ফসল",
    resultsCropsDesc: "আপনার মাটির পুষ্টি উপাদান ও মৌসুম অনুযায়ী।",
    resultsSoilCorrections: "মাটি সংশোধন",
    resultsFertilizerPlan: "সার পরিকল্পনা",
    resultsNoCorrections: "মাটির ভারসাম্য ভালো। বড় সংশোধনের প্রয়োজন নেই।",
    resultsSuitabilityScore: "উপযুক্ততার স্কোর",
    resultsDosage: "পরিমাণ",
    resultsTiming: "সময়",
    resultsExplanationTitle: "বিস্তারিত পরামর্শ",
    resultsEnglishLabel: "ইংরেজি",
    adminTitle: "অ্যাডমিন ড্যাশবোর্ড",
    adminSubtitle: "সমস্ত মাটি বিশ্লেষণ জমার সংক্ষিপ্ত বিবরণ।",
    adminTotalSubmissions: "মোট জমা",
    adminTodayAnalyses: "আজকের বিশ্লেষণ",
    adminAvgPh: "গড় pH মাত্রা",
    adminTopCrop: "শীর্ষ ফসলের অনুরোধ",
    adminRecentSubmissions: "সাম্প্রতিক জমা",
    adminTopCrops: "শীর্ষ সুপারিশকৃত ফসল",
    adminSeasonBreakdown: "মৌসুম বিভাজন",
    detectedLanguage: "সনাক্তকৃত ভাষা",
  },
  mr: {
    appSubtitle: "मृद आरोग्य सल्लागार",
    navNewAnalysis: "नवीन विश्लेषण",
    navDashboard: "डॅशबोर्ड",
    formTitle: "मृद आरोग्य विश्लेषण",
    formSubtitle: "वैयक्तिक पीक शिफारसी मिळवण्यासाठी मातीच्या चाचणीचे तपशील भरा.",
    sectionSampleInfo: "नमुना माहिती",
    sectionSampleInfoDesc: "तुमच्या शेती आणि मातीच्या नमुन्याची मूलभूत माहिती द्या.",
    sectionSoilReadings: "माती चाचणी मूल्ये",
    labelFarmerName: "शेतकऱ्याचे नाव (पर्यायी)",
    labelLocation: "जिल्हा / ठिकाण",
    labelSeason: "पीक हंगाम",
    labelWater: "पाण्याची उपलब्धता",
    labelPh: "pH पातळी (0-14)",
    labelNitrogen: "नायट्रोजन (N) किलो/हेक्टर",
    labelPhosphorus: "फॉस्फरस (P) किलो/हेक्टर",
    labelPotassium: "पोटॅशियम (K) किलो/हेक्टर",
    labelMoisture: "ओलावा (%)",
    labelPreferredCrop: "आवडते पीक (पर्यायी)",
    preferredCropHint: "मनात एखादे पीक असल्यास सांगा — योग्य सल्ला देऊ.",
    placeholderFarmerName: "उदा: रामराव पाटील",
    placeholderLocation: "उदा: सोलापूर, महाराष्ट्र",
    placeholderCrop: "उदा: ज्वारी, बाजरी, सोयाबीन",
    selectSeason: "हंगाम निवडा",
    selectWater: "निवडा",
    seasonKharif: "खरीप (पावसाळा)",
    seasonRabi: "रब्बी (हिवाळा)",
    seasonSummer: "उन्हाळी",
    waterLow: "कमी (पावसावर अवलंबून)",
    waterMedium: "मध्यम (अंशतः सिंचन)",
    waterHigh: "जास्त (पूर्ण सिंचन)",
    btnGetRecommendations: "शिफारसी मिळवा",
    btnAnalyzing: "नमुना विश्लेषण होत आहे...",
    btnDetectLocation: "माझे ठिकाण शोधा",
    btnDetecting: "शोधत आहे...",
    btnAnalyzeAnother: "दुसरा नमुना तपासा",
    gpsLocationDetected: "ठिकाण सापडले",
    gpsDetecting: "तुमचे ठिकाण शोधत आहे...",
    gpsError: "ठिकाण सापडले नाही",
    weatherTitle: "तुमच्या ठिकाणचे लाइव्ह हवामान",
    weatherTemp: "तापमान",
    weatherHumidity: "आर्द्रता",
    weatherGpsNote: "GPS द्वारे थेट माहिती",
    resultsTitle: "विश्लेषण निकाल",
    resultsGeneratedOn: "तयार केल्याची तारीख",
    resultsCropsTitle: "शीर्ष शिफारस केलेली पिके",
    resultsCropsDesc: "तुमच्या मातीचे पोषण आणि हंगामावर आधारित.",
    resultsSoilCorrections: "माती सुधारणा",
    resultsFertilizerPlan: "खत योजना",
    resultsNoCorrections: "मातीचा समतोल चांगला आहे. मोठ्या सुधारणेची गरज नाही.",
    resultsSuitabilityScore: "उपयुक्तता गुण",
    resultsDosage: "मात्रा",
    resultsTiming: "वेळ",
    resultsExplanationTitle: "सविस्तर सल्ला",
    resultsEnglishLabel: "इंग्रजी",
    adminTitle: "प्रशासन डॅशबोर्ड",
    adminSubtitle: "सर्व माती विश्लेषण सादरीकरणांचे विहंगावलोकन.",
    adminTotalSubmissions: "एकूण सादरीकरणे",
    adminTodayAnalyses: "आजचे विश्लेषण",
    adminAvgPh: "सरासरी pH पातळी",
    adminTopCrop: "शीर्ष पीक विनंती",
    adminRecentSubmissions: "अलीकडील सादरीकरणे",
    adminTopCrops: "शीर्ष शिफारस पिके",
    adminSeasonBreakdown: "हंगाम विभाजन",
    detectedLanguage: "आढळलेली भाषा",
  },
  gu: {
    appSubtitle: "જમીન આરોગ્ય સલાહકાર",
    navNewAnalysis: "નવું વિશ્લેષણ",
    navDashboard: "ડૅશબોર્ડ",
    formTitle: "જમીન આરોગ્ય વિશ્લેષણ",
    formSubtitle: "વ્યક્તિગત પાક ભલામણો મેળવવા માટે તમારી જમીન પરીક્ષણ વિગતો દાખલ કરો.",
    sectionSampleInfo: "નમૂના માહિતી",
    sectionSampleInfoDesc: "તમારી ખેતી અને જમીન નમૂના વિષે મૂળ વિગતો આપો.",
    sectionSoilReadings: "જમીન પરીક્ષણ માપ",
    labelFarmerName: "ખેડૂતનું નામ (વૈકલ્પિક)",
    labelLocation: "જિલ્લો / સ્થળ",
    labelSeason: "પાક ઋતુ",
    labelWater: "પાણીની ઉપલબ્ધતા",
    labelPh: "pH સ્તર (0-14)",
    labelNitrogen: "નાઇટ્રોજન (N) કિ.ગ્રા/હેક્ટર",
    labelPhosphorus: "ફૉસ્ફરસ (P) કિ.ગ્રા/હેક્ટર",
    labelPotassium: "પોટેશિયમ (K) કિ.ગ્રા/હેક્ટર",
    labelMoisture: "ભેજ (%)",
    labelPreferredCrop: "પ્રિય પાક (વૈકલ્પિક)",
    preferredCropHint: "મનમાં કોઈ પાક હોય તો જણાવો — યોગ્ય સલાહ આપીશું.",
    placeholderFarmerName: "ઉ.દ.: રામભાઈ પટેલ",
    placeholderLocation: "ઉ.દ.: સુરત, ગુજરાત",
    placeholderCrop: "ઉ.દ.: ઘઉં, ડાંગર, કપાસ",
    selectSeason: "ઋતુ પસંદ કરો",
    selectWater: "પસંદ કરો",
    seasonKharif: "ખરીફ (ચોમાસું)",
    seasonRabi: "રવિ (શિયાળો)",
    seasonSummer: "ઉનાળો",
    waterLow: "ઓછું (ફક્ત વરસાદ)",
    waterMedium: "મધ્યમ (આંશિક સિંચાઈ)",
    waterHigh: "વધુ (સંપૂર્ણ સિંચાઈ)",
    btnGetRecommendations: "ભલામણો મેળવો",
    btnAnalyzing: "નમૂનું વિશ્લેષણ થઈ રહ્યું છે...",
    btnDetectLocation: "મારું સ્થળ શોધો",
    btnDetecting: "શોધી રહ્યું છે...",
    btnAnalyzeAnother: "બીજો નમૂનો તપાસો",
    gpsLocationDetected: "સ્થળ મળ્યું",
    gpsDetecting: "તમારું સ્થળ શોધી રહ્યું છે...",
    gpsError: "સ્થળ મળ્યું નહીં",
    weatherTitle: "તમારા સ્થળનું લાઇવ હવામાન",
    weatherTemp: "તાપમાન",
    weatherHumidity: "ભેજ",
    weatherGpsNote: "GPS દ્વારા સીધો ડેટા",
    resultsTitle: "વિશ્લેષણ પરિણામ",
    resultsGeneratedOn: "બનાવ્યાની તારીખ",
    resultsCropsTitle: "ટોચના ભલામણ કરેલા પાક",
    resultsCropsDesc: "તમારી જમીનના પોષણ અને ઋતુ અનુસાર.",
    resultsSoilCorrections: "જમીન સુધારણા",
    resultsFertilizerPlan: "ખાતર યોજના",
    resultsNoCorrections: "જમીનું સંતુલન સારું છે. મોટી સુધારણાની જરૂર નથી.",
    resultsSuitabilityScore: "યોગ્યતા સ્કોર",
    resultsDosage: "માત્રા",
    resultsTiming: "સમય",
    resultsExplanationTitle: "વિગતવાર સલાહ",
    resultsEnglishLabel: "અંગ્રેજી",
    adminTitle: "એડમિન ડૅશબોર્ડ",
    adminSubtitle: "તમામ જમીન વિશ્લેષણ સমર્પણોની ઝાંખી.",
    adminTotalSubmissions: "કુલ સમર્પણ",
    adminTodayAnalyses: "આજના વિશ્લેષણ",
    adminAvgPh: "સરેરાશ pH સ્તર",
    adminTopCrop: "ટોચની પાક વિનંતી",
    adminRecentSubmissions: "તાજેતરના સમર્પણ",
    adminTopCrops: "ટોચના ભલામણ પાક",
    adminSeasonBreakdown: "ઋતુ વિભાજન",
    detectedLanguage: "શોધાઈ ભાષા",
  },
  pa: {
    appSubtitle: "ਮਿੱਟੀ ਸਿਹਤ ਸਲਾਹਕਾਰ",
    navNewAnalysis: "ਨਵਾਂ ਵਿਸ਼ਲੇਸ਼ਣ",
    navDashboard: "ਡੈਸ਼ਬੋਰਡ",
    formTitle: "ਮਿੱਟੀ ਸਿਹਤ ਵਿਸ਼ਲੇਸ਼ਣ",
    formSubtitle: "ਨਿੱਜੀ ਫ਼ਸਲ ਸਿਫਾਰਸ਼ਾਂ ਲਈ ਆਪਣੀ ਮਿੱਟੀ ਜਾਂਚ ਦੀਆਂ ਜਾਣਕਾਰੀਆਂ ਦਰਜ ਕਰੋ।",
    sectionSampleInfo: "ਨਮੂਨਾ ਜਾਣਕਾਰੀ",
    sectionSampleInfoDesc: "ਆਪਣੇ ਖੇਤ ਅਤੇ ਮਿੱਟੀ ਦੇ ਨਮੂਨੇ ਬਾਰੇ ਮੁੱਢਲੀ ਜਾਣਕਾਰੀ ਦਿਓ।",
    sectionSoilReadings: "ਮਿੱਟੀ ਜਾਂਚ ਮੁੱਲ",
    labelFarmerName: "ਕਿਸਾਨ ਦਾ ਨਾਮ (ਵਿਕਲਪਿਕ)",
    labelLocation: "ਜ਼ਿਲ੍ਹਾ / ਸਥਾਨ",
    labelSeason: "ਫ਼ਸਲ ਰੁੱਤ",
    labelWater: "ਪਾਣੀ ਦੀ ਉਪਲਬਧਤਾ",
    labelPh: "pH ਪੱਧਰ (0-14)",
    labelNitrogen: "ਨਾਈਟ੍ਰੋਜਨ (N) ਕਿ.ਗ੍ਰਾ/ਹੈਕਟੇਅਰ",
    labelPhosphorus: "ਫਾਸਫੋਰਸ (P) ਕਿ.ਗ੍ਰਾ/ਹੈਕਟੇਅਰ",
    labelPotassium: "ਪੋਟਾਸ਼ੀਅਮ (K) ਕਿ.ਗ੍ਰਾ/ਹੈਕਟੇਅਰ",
    labelMoisture: "ਨਮੀ (%)",
    labelPreferredCrop: "ਪਸੰਦੀਦਾ ਫ਼ਸਲ (ਵਿਕਲਪਿਕ)",
    preferredCropHint: "ਜੇ ਕੋਈ ਫ਼ਸਲ ਮਨ ਵਿੱਚ ਹੋਵੇ, ਦੱਸੋ — ਸਹੀ ਸਲਾਹ ਦੇਵਾਂਗੇ।",
    placeholderFarmerName: "ਜਿਵੇਂ: ਗੁਰਮੀਤ ਸਿੰਘ",
    placeholderLocation: "ਜਿਵੇਂ: ਲੁਧਿਆਣਾ, ਪੰਜਾਬ",
    placeholderCrop: "ਜਿਵੇਂ: ਕਣਕ, ਝੋਨਾ, ਮੱਕੀ",
    selectSeason: "ਰੁੱਤ ਚੁਣੋ",
    selectWater: "ਚੁਣੋ",
    seasonKharif: "ਖ਼ਰੀਫ਼ (ਸਾਉਣੀ)",
    seasonRabi: "ਰਬੀ (ਹਾੜੀ)",
    seasonSummer: "ਗਰਮੀਆਂ",
    waterLow: "ਘੱਟ (ਸਿਰਫ਼ ਮੀਂਹ)",
    waterMedium: "ਦਰਮਿਆਨਾ (ਅੰਸ਼ਕ ਸਿੰਚਾਈ)",
    waterHigh: "ਵੱਧ (ਪੂਰੀ ਸਿੰਚਾਈ)",
    btnGetRecommendations: "ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    btnAnalyzing: "ਨਮੂਨਾ ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    btnDetectLocation: "ਮੇਰਾ ਸਥਾਨ ਪਤਾ ਲਾਓ",
    btnDetecting: "ਪਤਾ ਲਾਇਆ ਜਾ ਰਿਹਾ ਹੈ...",
    btnAnalyzeAnother: "ਦੂਜਾ ਨਮੂਨਾ ਜਾਂਚੋ",
    gpsLocationDetected: "ਸਥਾਨ ਮਿਲਿਆ",
    gpsDetecting: "ਤੁਹਾਡਾ ਸਥਾਨ ਲੱਭਿਆ ਜਾ ਰਿਹਾ ਹੈ...",
    gpsError: "ਸਥਾਨ ਲੱਭਣਾ ਸੰਭਵ ਨਹੀਂ ਹੋਇਆ",
    weatherTitle: "ਤੁਹਾਡੇ ਸਥਾਨ ਦਾ ਲਾਈਵ ਮੌਸਮ",
    weatherTemp: "ਤਾਪਮਾਨ",
    weatherHumidity: "ਨਮੀ",
    weatherGpsNote: "GPS ਤੋਂ ਸਿੱਧਾ ਡੇਟਾ",
    resultsTitle: "ਵਿਸ਼ਲੇਸ਼ਣ ਨਤੀਜੇ",
    resultsGeneratedOn: "ਤਿਆਰ ਕੀਤਾ",
    resultsCropsTitle: "ਚੋਟੀ ਦੀਆਂ ਸਿਫਾਰਸ਼ੀ ਫ਼ਸਲਾਂ",
    resultsCropsDesc: "ਤੁਹਾਡੀ ਮਿੱਟੀ ਦੇ ਪੌਸ਼ਟਿਕ ਤੱਤ ਅਤੇ ਰੁੱਤ ਦੇ ਆਧਾਰ 'ਤੇ।",
    resultsSoilCorrections: "ਮਿੱਟੀ ਸੁਧਾਰ",
    resultsFertilizerPlan: "ਖਾਦ ਯੋਜਨਾ",
    resultsNoCorrections: "ਮਿੱਟੀ ਦਾ ਸੰਤੁਲਨ ਠੀਕ ਹੈ। ਕੋਈ ਵੱਡਾ ਸੁਧਾਰ ਲੋੜੀਂਦਾ ਨਹੀਂ।",
    resultsSuitabilityScore: "ਅਨੁਕੂਲਤਾ ਸਕੋਰ",
    resultsDosage: "ਮਾਤਰਾ",
    resultsTiming: "ਸਮਾਂ",
    resultsExplanationTitle: "ਵਿਸਥਾਰਤ ਸਲਾਹ",
    resultsEnglishLabel: "ਅੰਗਰੇਜ਼ੀ",
    adminTitle: "ਐਡਮਿਨ ਡੈਸ਼ਬੋਰਡ",
    adminSubtitle: "ਸਾਰੇ ਮਿੱਟੀ ਵਿਸ਼ਲੇਸ਼ਣ ਜਮ੍ਹਾਂ ਕਰਵਾਉਣ ਦਾ ਸੰਖੇਪ।",
    adminTotalSubmissions: "ਕੁੱਲ ਜਮ੍ਹਾਂ",
    adminTodayAnalyses: "ਅੱਜ ਦੇ ਵਿਸ਼ਲੇਸ਼ਣ",
    adminAvgPh: "ਔਸਤ pH ਪੱਧਰ",
    adminTopCrop: "ਚੋਟੀ ਦੀ ਫ਼ਸਲ ਬੇਨਤੀ",
    adminRecentSubmissions: "ਹਾਲੀਆ ਜਮ੍ਹਾਂ",
    adminTopCrops: "ਚੋਟੀ ਦੀਆਂ ਸਿਫਾਰਸ਼ੀ ਫ਼ਸਲਾਂ",
    adminSeasonBreakdown: "ਰੁੱਤ ਵੰਡ",
    detectedLanguage: "ਪਤਾ ਲੱਗੀ ਭਾਸ਼ਾ",
  },
  or: {
    appSubtitle: "ମାଟି ସ୍ୱାସ୍ଥ୍ୟ ପରାମର୍ଶଦାତା",
    navNewAnalysis: "ନୂଆ ବିଶ୍ଳେଷଣ",
    navDashboard: "ଡ୍ୟାଶବୋର୍ଡ",
    formTitle: "ମାଟି ସ୍ୱାସ୍ଥ୍ୟ ବିଶ୍ଳେଷଣ",
    formSubtitle: "ବ୍ୟକ୍ତିଗତ ଫସଲ ସୁପାରିଶ ପାଇଁ ଆପଣଙ୍କ ମାଟି ପରୀକ୍ଷା ବିବରଣୀ ଦିଅନ୍ତୁ।",
    sectionSampleInfo: "ନମୁନା ତଥ୍ୟ",
    sectionSampleInfoDesc: "ଆପଣଙ୍କ ଜମି ଓ ମାଟି ନମୁନା ବିଷୟରେ ମୂଳ ତଥ୍ୟ ଦିଅନ୍ତୁ।",
    sectionSoilReadings: "ମାଟି ପରୀକ୍ଷା ମୂଲ୍ୟ",
    labelFarmerName: "ଚାଷୀଙ୍କ ନାମ (ଐଚ୍ଛିକ)",
    labelLocation: "ଜିଲ୍ଲା / ସ୍ଥାନ",
    labelSeason: "ଫସଲ ଋତୁ",
    labelWater: "ଜଳ ଉପଲବ୍ଧତା",
    labelPh: "pH ସ୍ତର (0-14)",
    labelNitrogen: "ନାଇଟ୍ରୋଜେନ (N) କି.ଗ୍ରା/ହେ.",
    labelPhosphorus: "ଫସଫରସ (P) କି.ଗ୍ରା/ହେ.",
    labelPotassium: "ପୋଟ୍ୟାସିୟମ (K) କି.ଗ୍ରା/ହେ.",
    labelMoisture: "ଆର୍ଦ୍ରତା (%)",
    labelPreferredCrop: "ପସନ୍ଦର ଫସଲ (ଐଚ୍ଛିକ)",
    preferredCropHint: "ଯଦି ଗୋଟିଏ ଫସଲ ମନରେ ଅଛି, ଜଣାଇଦିଅନ୍ତୁ।",
    placeholderFarmerName: "ଉ.ଦ: ରାମ ଚଢ଼ଇ",
    placeholderLocation: "ଉ.ଦ: କଟକ, ଓଡ଼ିଶା",
    placeholderCrop: "ଉ.ଦ: ଧାନ, ଗହମ, ମୁଗ",
    selectSeason: "ଋତୁ ବାଛନ୍ତୁ",
    selectWater: "ବାଛନ୍ତୁ",
    seasonKharif: "ଖରିଫ (ବର୍ଷା)",
    seasonRabi: "ରବି (ଶୀତ)",
    seasonSummer: "ଗ୍ରୀଷ୍ମ",
    waterLow: "କମ (ବର୍ଷା ଜଳ)",
    waterMedium: "ମଧ୍ୟମ (ଆଂଶିକ ସେଚ)",
    waterHigh: "ଅଧିକ (ପୂର୍ଣ ସେଚ)",
    btnGetRecommendations: "ସୁପାରିଶ ପାଆନ୍ତୁ",
    btnAnalyzing: "ନମୁନା ବିଶ୍ଳେଷଣ ହେଉଛି...",
    btnDetectLocation: "ମୋ ସ୍ଥାନ ଚିହ୍ନଟ କରନ୍ତୁ",
    btnDetecting: "ଚିହ୍ନଟ ହେଉଛି...",
    btnAnalyzeAnother: "ଅନ୍ୟ ନମୁନା ପରୀକ୍ଷା",
    gpsLocationDetected: "ସ୍ଥାନ ଚିହ୍ନଟ ହେଲା",
    gpsDetecting: "ଆପଣଙ୍କ ସ୍ଥାନ ଖୋଜାଯାଉଛି...",
    gpsError: "ସ୍ଥାନ ଚିହ୍ନଟ ହୋଇପାରିଲା ନାହିଁ",
    weatherTitle: "ଆପଣଙ୍କ ସ୍ଥାନର ଲାଇଭ ଆବହାୱା",
    weatherTemp: "ତାପମାତ୍ରା",
    weatherHumidity: "ଆର୍ଦ୍ରତା",
    weatherGpsNote: "GPS ଦ୍ୱାରା ସିଧା ତଥ୍ୟ",
    resultsTitle: "ବିଶ୍ଳେଷଣ ଫଳ",
    resultsGeneratedOn: "ପ୍ରସ୍ତୁତ ତାରିଖ",
    resultsCropsTitle: "ଶ୍ରେଷ୍ଠ ସୁପାରିଶ ଫସଲ",
    resultsCropsDesc: "ଆପଣଙ୍କ ମାଟି ଓ ଋତୁ ଆଧାରରେ।",
    resultsSoilCorrections: "ମାଟି ସୁଧାର",
    resultsFertilizerPlan: "ସାର ଯୋଜନା",
    resultsNoCorrections: "ମାଟି ସନ୍ତୁଳନ ଭଲ ଅଛି। ବଡ ସୁଧାର ଦରକାର ନାହିଁ।",
    resultsSuitabilityScore: "ଉପଯୁକ୍ତ ସ୍କୋର",
    resultsDosage: "ମାତ୍ରା",
    resultsTiming: "ସମୟ",
    resultsExplanationTitle: "ବିସ୍ତୃତ ପରାମର୍ଶ",
    resultsEnglishLabel: "ଇଂରାଜୀ",
    adminTitle: "ଆଡମିନ ଡ୍ୟାଶବୋର୍ଡ",
    adminSubtitle: "ସମସ୍ତ ମାଟି ବିଶ୍ଳେଷଣ ଦାଖଲର ସଂକ୍ଷିପ୍ତ ଦୃଶ୍ୟ।",
    adminTotalSubmissions: "ମୋଟ ଦାଖଲ",
    adminTodayAnalyses: "ଆଜିର ବିଶ୍ଳେଷଣ",
    adminAvgPh: "ହାରାହାରି pH ସ୍ତର",
    adminTopCrop: "ଶ୍ରେଷ୍ଠ ଫସଲ ଅନୁରୋଧ",
    adminRecentSubmissions: "ସାମ୍ପ୍ରତିକ ଦାଖଲ",
    adminTopCrops: "ଶ୍ରେଷ୍ଠ ସୁପାରିଶ ଫସଲ",
    adminSeasonBreakdown: "ଋତୁ ବିଭାଜନ",
    detectedLanguage: "ଚିହ୍ନଟ ଭାଷା",
  },
};

const SUPPORTED_LANGS: LangCode[] = ["ta", "hi", "te", "kn", "ml", "bn", "mr", "gu", "pa", "or", "en"];

function detectLanguage(): LangCode {
  const langs = navigator.languages?.length ? navigator.languages : [navigator.language];
  for (const lang of langs) {
    const code = lang.split("-")[0].toLowerCase() as LangCode;
    if (SUPPORTED_LANGS.includes(code)) return code;
  }
  return "en";
}

interface LanguageContextType {
  lang: LangCode;
  t: Translations;
  setLang: (l: LangCode) => void;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<LangCode>(() => detectLanguage());

  useEffect(() => {
    const detected = detectLanguage();
    setLang(detected);
  }, []);

  const t = translations[lang] ?? translations.en;

  return (
    <LanguageContext.Provider value={{ lang, t, setLang }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export { translations };
